using System;

namespace EnderCode.osuBackupAndRestore
{
    /// <summary>
    /// Enum a nyelvi szövegek lekéréséhez
    /// </summary>
    enum UIElements : byte
    {
        WindowTitle,
        HeadLine,
        CurrentBackupDir,
        BackupDirNotFound,
        NoBackupDir,
        NoSourceFound,
        Commands,
        LastOp,
        LastOpTime,
        MissingLastRunInfo,
        SafeguardFound,
        Prompt,
        SeeYa,
        ErrorPrefix,
        GettingFiles,
        LaunchToast,
        AwaitKeyToast,
        RepairToast,
        CopyToast,
        FileNotFoundEx,
        Win32Ex,
        ProcessEnded,
        FileInfoPart1,
        FileInfoPart2,
        FileInfoPart3,
        FileInfoPart4,
        FinalSizePart1,
        FinalSizePart2,
        FinalSizePart3,
        ErrorDetails,
        NoCurrentBackupDir,
        NewDir,
        CorrectQuestionStr,
        CreateNew,
        WarnPrefix,
        QueryProcess,
        MultiProcessWeirdness,
        NoProcess,
        WhatTheFuckWasThat,
        ProcessCaught,
        PartialDownloadedMaps,
        PartialNewMaps,
        QuestionLaunch,
        QuestionSure,
        Done,
        Aborted,
        QuestionDelete,
        SafeguardDeleteCmd,
        VersionString,
        LibVersion,
        MapIDCollusion,
        CollusionDialog,
        FolderBrowsing,
        InstallNotFound,
        BrowseAbort,
        BrowseFolder,
        BrowseSuccess,
        BrowseBackup,
        BrowseBackupAbort,
        AbortedOrNotFound,
        EarlyException
    }
}