//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnderCode.osu_backupAndRestore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnderCode.osu_backupAndRestore.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string AbortedEng {
            get {
                return ResourceManager.GetString("AbortedEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elvetve.
        /// </summary>
        internal static string AbortedHun {
            get {
                return ResourceManager.GetString("AbortedHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key to continue....
        /// </summary>
        internal static string AwaitKeyToastEng {
            get {
                return ResourceManager.GetString("AwaitKeyToastEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyomj egy gombot a folytatáshoz....
        /// </summary>
        internal static string AwaitKeyToastHun {
            get {
                return ResourceManager.GetString("AwaitKeyToastHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last operation file doesn&apos;t exist!\nPlease specify backup directory by hand first!.
        /// </summary>
        internal static string BackupDirNotFoundEng {
            get {
                return ResourceManager.GetString("BackupDirNotFoundEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utolsó mentés fájlja nem létezik!\nAdja meg a biztonsági  mentés helyét kézzel előbb!.
        /// </summary>
        internal static string BackupDirNotFoundHun {
            get {
                return ResourceManager.GetString("BackupDirNotFoundHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to filter them out? [(Y)es/(N)o].
        /// </summary>
        internal static string CollusionDialogEng {
            get {
                return ResourceManager.GetString("CollusionDialogEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ki szeretnéd szűrni őket? [(I)gen/(N)em].
        /// </summary>
        internal static string CollusionDialogHun {
            get {
                return ResourceManager.GetString("CollusionDialogHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:\n%fB - Backup  %fR - Restore  %fP - Repair  %fL - Launch \n%fE - Catch game process  %fC - Change backup dir  \n%fE%fn%ft%fe%fr - backup and go  %fF%f1 - Change language  %fQ - Exit\n%fS%fh%fi%ff%ft %f+ %fL \  Autoclose after\n%fS%fh%fi%ff%ft %f+ %fB /  the game ended.
        /// </summary>
        internal static string CommandsEng {
            get {
                return ResourceManager.GetString("CommandsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parancsok:\n%fB - Biztosági mentés  %fR - Helyreállítás  %fP - Javítás  %fL - Indítás\n%fE - Játékfolyamat elfogása  %fC - Bizt.mentés könyvtárának megadása\n%fE%fn%ft%fe%fr - Mentés és indítás  %fF%f1 - Nyelv váltása  %fQ - Kilépés\n%fS%fh%fi%ff%ft %f+ %fL \  Auto-bezárás\n%fS%fh%fi%ff%ft %f+ %fB /  miután a játék leállt.
        /// </summary>
        internal static string CommandsHun {
            get {
                return ResourceManager.GetString("CommandsHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files to %d....
        /// </summary>
        internal static string CopyToastEng {
            get {
                return ResourceManager.GetString("CopyToastEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájlok másolása %d helyre....
        /// </summary>
        internal static string CopyToastHun {
            get {
                return ResourceManager.GetString("CopyToastHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is that correct? [(Y)es/(N)o].
        /// </summary>
        internal static string CorrectQuestionStrEng {
            get {
                return ResourceManager.GetString("CorrectQuestionStrEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez megfelelő? [(I)gen/(N)em].
        /// </summary>
        internal static string CorrectQuestionStrHun {
            get {
                return ResourceManager.GetString("CorrectQuestionStrHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exits!\nCreate one? [(Y)es/(N)o].
        /// </summary>
        internal static string CreateNewEng {
            get {
                return ResourceManager.GetString("CreateNewEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Könyvtár nem létezik!\nCreate one? [(I)gen/(N)em].
        /// </summary>
        internal static string CreateNewHun {
            get {
                return ResourceManager.GetString("CreateNewHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current backup dir.
        /// </summary>
        internal static string CurrentBackupDirEng {
            get {
                return ResourceManager.GetString("CurrentBackupDirEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés jelenelegi helye.
        /// </summary>
        internal static string CurrentBackupDirHun {
            get {
                return ResourceManager.GetString("CurrentBackupDirHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string DoneEng {
            get {
                return ResourceManager.GetString("DoneEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kész!.
        /// </summary>
        internal static string DoneHun {
            get {
                return ResourceManager.GetString("DoneHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use enviromental variables!.
        /// </summary>
        internal static string EnvVarInfoEng {
            get {
                return ResourceManager.GetString("EnvVarInfoEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Használhatsz környezetiváltozókat is!.
        /// </summary>
        internal static string EnvVarInfoHun {
            get {
                return ResourceManager.GetString("EnvVarInfoHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details.
        /// </summary>
        internal static string ErrorDetailsEng {
            get {
                return ResourceManager.GetString("ErrorDetailsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba részletei.
        /// </summary>
        internal static string ErrorDetailsHun {
            get {
                return ResourceManager.GetString("ErrorDetailsHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR].
        /// </summary>
        internal static string ErrorPrefixEng {
            get {
                return ResourceManager.GetString("ErrorPrefixEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HIBA].
        /// </summary>
        internal static string ErrorPrefixHun {
            get {
                return ResourceManager.GetString("ErrorPrefixHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileInfoPart1Eng {
            get {
                return ResourceManager.GetString("FileInfoPart1Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl.
        /// </summary>
        internal static string FileInfoPart1Hun {
            get {
                return ResourceManager.GetString("FileInfoPart1Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found at.
        /// </summary>
        internal static string FileInfoPart2Eng {
            get {
                return ResourceManager.GetString("FileInfoPart2Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megtalálva.
        /// </summary>
        internal static string FileInfoPart2Hun {
            get {
                return ResourceManager.GetString("FileInfoPart2Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string FileInfoPart3Eng {
            get {
                return ResourceManager.GetString("FileInfoPart3Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to helyen, mérete.
        /// </summary>
        internal static string FileInfoPart3Hun {
            get {
                return ResourceManager.GetString("FileInfoPart3Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        internal static string FileInfoPart4Eng {
            get {
                return ResourceManager.GetString("FileInfoPart4Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FileInfoPart4Hun {
            get {
                return ResourceManager.GetString("FileInfoPart4Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch target not found! Is the game installed?.
        /// </summary>
        internal static string FileNotFoundExEng {
            get {
                return ResourceManager.GetString("FileNotFoundExEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indítási cél nem találtható! Telepítve van a játék?.
        /// </summary>
        internal static string FileNotFoundExHun {
            get {
                return ResourceManager.GetString("FileNotFoundExHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final size.
        /// </summary>
        internal static string FinalSizePart1Eng {
            get {
                return ResourceManager.GetString("FinalSizePart1Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végső méret.
        /// </summary>
        internal static string FinalSizePart1Hun {
            get {
                return ResourceManager.GetString("FinalSizePart1Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in .
        /// </summary>
        internal static string FinalSizePart2Eng {
            get {
                return ResourceManager.GetString("FinalSizePart2Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinalSizePart2Hun {
            get {
                return ResourceManager.GetString("FinalSizePart2Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string FinalSizePart3Eng {
            get {
                return ResourceManager.GetString("FinalSizePart3Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fájlban.
        /// </summary>
        internal static string FinalSizePart3Hun {
            get {
                return ResourceManager.GetString("FinalSizePart3Hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting files....
        /// </summary>
        internal static string GettingFilesEng {
            get {
                return ResourceManager.GetString("GettingFilesEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájlok beszerzése....
        /// </summary>
        internal static string GettingFilesHun {
            get {
                return ResourceManager.GetString("GettingFilesHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu! backup, restore and repair tool.
        /// </summary>
        internal static string HeadLineEng {
            get {
                return ResourceManager.GetString("HeadLineEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu! biztonsági mentés, helyreállító és javító eszköz.
        /// </summary>
        internal static string HeadLineHun {
            get {
                return ResourceManager.GetString("HeadLineHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last operation.
        /// </summary>
        internal static string LastOpEng {
            get {
                return ResourceManager.GetString("LastOpEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utolsó művelet.
        /// </summary>
        internal static string LastOpHun {
            get {
                return ResourceManager.GetString("LastOpHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LastOpTimeEng {
            get {
                return ResourceManager.GetString("LastOpTimeEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideje.
        /// </summary>
        internal static string LastOpTimeHun {
            get {
                return ResourceManager.GetString("LastOpTimeHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching osu!....
        /// </summary>
        internal static string LaunchToastEng {
            get {
                return ResourceManager.GetString("LaunchToastEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu! indítása....
        /// </summary>
        internal static string LaunchToastHun {
            get {
                return ResourceManager.GetString("LaunchToastHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utils library version: .
        /// </summary>
        internal static string LibVersionEng {
            get {
                return ResourceManager.GetString("LibVersionEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segéd könyvtár verzió: .
        /// </summary>
        internal static string LibVersionHun {
            get {
                return ResourceManager.GetString("LibVersionHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unimported map ID(s) collide with already imported ones..
        /// </summary>
        internal static string MapIDCollusionEng {
            get {
                return ResourceManager.GetString("MapIDCollusionEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to importálatlan pálya azonosítója ütközik már meglévő pályákéval..
        /// </summary>
        internal static string MapIDCollusionHun {
            get {
                return ResourceManager.GetString("MapIDCollusionHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No last run info file found!\nThis file will be created after a backup or restore..
        /// </summary>
        internal static string MissingLastRunInfoEng {
            get {
                return ResourceManager.GetString("MissingLastRunInfoEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utolsó futást tartalmazó fájl hiányzik!\nEz a fájl egy bizt.mentés vagy visszaállítás után elkészítésre kerül. .
        /// </summary>
        internal static string MissingLastRunInfoHun {
            get {
                return ResourceManager.GetString("MissingLastRunInfoHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple running processes are found! (Something&apos;s not right here...).
        /// </summary>
        internal static string MultiProcessWeirdnessEng {
            get {
                return ResourceManager.GetString("MultiProcessWeirdnessEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Több futó folyamatot találtam! (Valami itt nem stimmel...).
        /// </summary>
        internal static string MultiProcessWeirdnessHun {
            get {
                return ResourceManager.GetString("MultiProcessWeirdnessHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New backup directory.
        /// </summary>
        internal static string NewDirEng {
            get {
                return ResourceManager.GetString("NewDirEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új bizt.mentés könyvtára.
        /// </summary>
        internal static string NewDirHun {
            get {
                return ResourceManager.GetString("NewDirHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No directory specified.
        /// </summary>
        internal static string NoBackupDirEng {
            get {
                return ResourceManager.GetString("NoBackupDirEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs könyvtár megadva.
        /// </summary>
        internal static string NoBackupDirHun {
            get {
                return ResourceManager.GetString("NoBackupDirHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not exist!.
        /// </summary>
        internal static string NoCurrentBackupDirEng {
            get {
                return ResourceManager.GetString("NoCurrentBackupDirEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem létezik!.
        /// </summary>
        internal static string NoCurrentBackupDirHun {
            get {
                return ResourceManager.GetString("NoCurrentBackupDirHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No running instance of the game has been found!.
        /// </summary>
        internal static string NoProcessEng {
            get {
                return ResourceManager.GetString("NoProcessEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem találtam egy futó példányát sem a játéknak!.
        /// </summary>
        internal static string NoProcessHun {
            get {
                return ResourceManager.GetString("NoProcessHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory not found! Game installation or backup directory not found.\nInstall the game first or make sure that it is at the right place!.
        /// </summary>
        internal static string NoSourceFoundEng {
            get {
                return ResourceManager.GetString("NoSourceFoundEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forrás könyvtár nem található! Játék telepítés vagy bizt.mentés könyvtára nem található!\nTelepítsd a játékot elősször vagy bizonyosodj meg róla, hogy jó helyen van!.
        /// </summary>
        internal static string NoSourceFoundHun {
            get {
                return ResourceManager.GetString("NoSourceFoundHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maps are downloaded!.
        /// </summary>
        internal static string PartialDownloadedMapsEng {
            get {
                return ResourceManager.GetString("PartialDownloadedMapsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pályák letöltve!.
        /// </summary>
        internal static string PartialDownloadedMapsHun {
            get {
                return ResourceManager.GetString("PartialDownloadedMapsHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new maps found!.
        /// </summary>
        internal static string PartialNewMapsEng {
            get {
                return ResourceManager.GetString("PartialNewMapsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to új pályát találtam!.
        /// </summary>
        internal static string PartialNewMapsHun {
            get {
                return ResourceManager.GetString("PartialNewMapsHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proccess caught, waiting for exit....
        /// </summary>
        internal static string ProcessCaughtEng {
            get {
                return ResourceManager.GetString("ProcessCaughtEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folyamat elfogva, várakozás kilépésre....
        /// </summary>
        internal static string ProcessCaughtHun {
            get {
                return ResourceManager.GetString("ProcessCaughtHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ended. Press a key in 6 seconds if not a restart!.
        /// </summary>
        internal static string ProcessEndedEng {
            get {
                return ResourceManager.GetString("ProcessEndedEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folyamat befejeződött. Nyomj egy gombot 6mp-n ha nem újraindítás!.
        /// </summary>
        internal static string ProcessEndedHun {
            get {
                return ResourceManager.GetString("ProcessEndedHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string PromptEng {
            get {
                return ResourceManager.GetString("PromptEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válasz.
        /// </summary>
        internal static string PromptHun {
            get {
                return ResourceManager.GetString("PromptHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for running game proccess....
        /// </summary>
        internal static string QueryProcessEng {
            get {
                return ResourceManager.GetString("QueryProcessEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Játékfolyamat keresése....
        /// </summary>
        internal static string QueryProcessHun {
            get {
                return ResourceManager.GetString("QueryProcessHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the safeguard.lock file? [(Y)es/(N)o].
        /// </summary>
        internal static string QuestionDeleteEng {
            get {
                return ResourceManager.GetString("QuestionDeleteEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törölni akarod a biztosági fájlt (safeguard.lock) [(I)gen/(N)em].
        /// </summary>
        internal static string QuestionDeleteHun {
            get {
                return ResourceManager.GetString("QuestionDeleteHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to launch? [(Y)es/(N)o].
        /// </summary>
        internal static string QuestionLaunchEng {
            get {
                return ResourceManager.GetString("QuestionLaunchEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szeretnéd indítani? [(I)gen/(N)em].
        /// </summary>
        internal static string QuestionLaunchHun {
            get {
                return ResourceManager.GetString("QuestionLaunchHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure? [(Y)es/(N)o].
        /// </summary>
        internal static string QuestionSureEng {
            get {
                return ResourceManager.GetString("QuestionSureEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos vagy benne? [(I)gen/(N)em].
        /// </summary>
        internal static string QuestionSureHun {
            get {
                return ResourceManager.GetString("QuestionSureHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting repair....
        /// </summary>
        internal static string RepairToastEng {
            get {
                return ResourceManager.GetString("RepairToastEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javítás megkezdése....
        /// </summary>
        internal static string RepairToastHun {
            get {
                return ResourceManager.GetString("RepairToastHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + D - Delete residual safeguard file (at your own risk).
        /// </summary>
        internal static string SafeguardCommandEng {
            get {
                return ResourceManager.GetString("SafeguardCommandEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + D - Visszamaradt biztonsági fájl törlése (saját felelősségre!).
        /// </summary>
        internal static string SafeguardCommandHun {
            get {
                return ResourceManager.GetString("SafeguardCommandHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ATTENTION]: The game did not exited safely! Restoring backup is highly recommended!.
        /// </summary>
        internal static string SafeguardFoundEng {
            get {
                return ResourceManager.GetString("SafeguardFoundEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FIGYELEM]: A játék nem záródott be megfelelően! A bizt.mentés helyreállítása nagyon ajánlott!.
        /// </summary>
        internal static string SafeguardFoundHun {
            get {
                return ResourceManager.GetString("SafeguardFoundHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See ya&apos;! :D.
        /// </summary>
        internal static string SeeYaEng {
            get {
                return ResourceManager.GetString("SeeYaEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csáó! :D.
        /// </summary>
        internal static string SeeYaHun {
            get {
                return ResourceManager.GetString("SeeYaHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool version: .
        /// </summary>
        internal static string VersionStringEng {
            get {
                return ResourceManager.GetString("VersionStringEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eszköz verziója: .
        /// </summary>
        internal static string VersionStringHun {
            get {
                return ResourceManager.GetString("VersionStringHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WARN].
        /// </summary>
        internal static string WarnPrefixEng {
            get {
                return ResourceManager.GetString("WarnPrefixEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FIGYELEM].
        /// </summary>
        internal static string WarnPrefixHun {
            get {
                return ResourceManager.GetString("WarnPrefixHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception!.
        /// </summary>
        internal static string WhatTheFuckWasThatEng {
            get {
                return ResourceManager.GetString("WhatTheFuckWasThatEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen hiba!.
        /// </summary>
        internal static string WhatTheFuckWasThatHun {
            get {
                return ResourceManager.GetString("WhatTheFuckWasThatHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process could not be launched! Execution failure!.
        /// </summary>
        internal static string Win32ExEng {
            get {
                return ResourceManager.GetString("Win32ExEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folyamat nem indítható el! Végrehajtási hiba!.
        /// </summary>
        internal static string Win32ExHun {
            get {
                return ResourceManager.GetString("Win32ExHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu! Game Tools.
        /// </summary>
        internal static string WindowTitleEng {
            get {
                return ResourceManager.GetString("WindowTitleEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu! Játék Eszközök.
        /// </summary>
        internal static string WindowTitleHun {
            get {
                return ResourceManager.GetString("WindowTitleHun", resourceCulture);
            }
        }
    }
}
